name: Continuous Delivery

on:
  pull_request:
    branches: develop

jobs:
  continous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 노드 ${{ matrix.node-version }} 버젼으로 실행
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      - name: EC2에서 CD 프로세스 실행
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_REMOTE_SSH_KEY  }}" > ~/.ssh/hipspot_server.pem
          chmod 600 ~/.ssh/hipspot_server.pem
          ssh -i "~/.ssh/hipspot_server.pem" -o StrictHostKeyChecking=no ${{secrets.EC2_USER}}@${{secrets.EC2_KNOWN_HOST}} "zsh ~/deploy.sh" 
          rm -f ~/.ssh/hipspot_server.pem
